version: '3.8'

services:
  zoo1:
    container_name: zoo1
    image: zookeeper:3.8
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ./zk-single-kafka-single/zoo1/data:/var/lib/zookeeper/data
      - ./zk-single-kafka-single/zoo1/log:/var/lib/zookeeper/log
    restart: always

  zoo2:
    container_name: zoo2
    image: zookeeper:3.8
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ./zk-single-kafka-single/zoo2/data:/var/lib/zookeeper/data
      - ./zk-single-kafka-single/zoo2/log:/var/lib/zookeeper/log
    restart: always

  zoo3:
    container_name: zoo3
    image: zookeeper:3.8
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    volumes:
      - ./zk-single-kafka-single/zoo3/data:/var/lib/zookeeper/data
      - ./zk-single-kafka-single/zoo3/log:/var/lib/zookeeper/log
    restart: always

  kafka1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - 9091:9091
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9091
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#  zk-web:
#    container_name: zk_web
#    image: goodguide/zk-web-docker
#    ports:
#      - 8080:8080
#    environment:
#      - ZKWEB_PORT=8080
#      - ZKWEB_CREDENTIALS=admin:hello
#      - ZKWEB_DEFAULT_NODE=localhost:2181/default-node
#    restart: always

#networks:
#  promnet:
#    driver: bridge


# docker-compose -f docker-compose-zookeeper.yml up -d